- index.js
- ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m
- Set setupPush function for ios
- Add clearAllNotifications function for android to index
> Set native module function on index

- android/src/main/java/cn/jpush/reactnativejpush/JPushModule.java
Closed [issue 89](https://github.com/jpush/jpush-react-native/issues/89)
> Set tags silent

- ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.h
- ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m
- package.json
Use`__has_include()` discussed in
https://github.com/Microsoft/react-native-code-push/pull/670#discussion_r96869599
> Support RN 0.39 and RN 0.40+

- index.d.ts
> Complete index.d.ts

- JPushConfiguration.js
> Fix moduleName undefined

- example/documents/Android Usage.md
Should import package first, otherwise it will report 'cannot find' error.
> Should import package

- index.d.ts
- index.js
- package.json
发现 typescript 声明文件在更新到2.5.5时被删掉了(72a51628c697002772382e0c5007c118c0387668)，就按2.6.6补充了一份。
> feat: add typescript declaration file

- android/src/main/res/layout-v21/push_notification.xml
- android/src/main/res/layout/push_notification.xml
- android/src/main/res/values-zh/jpush_string.xml
- package.json
> 更新部分layout资源

- example/App.js
- index.d.ts
fix addCustomMessageListener 方法报错问题
> fix addCustomMessageListener 方法报错问题

- example/ios/Podfile.lock
- example/package.json
- index.js
- ios/RCTJPushModule/JPUSHService.h
- ios/RCTJPushModule/RCTJPushModule.m
- package.json
更新iOS Jpush4.8.1，新增对外API：设置用户属性。对外版本号294
> 更新iOS Jpush4.8.1，新增对外API：设置用户属性。对外版本号294

- example/ios/example/AppDelegate.m
> 【iOS】解决没有初始化，但是会请求通知权限弹窗的问题

- example/App.js
- example/ios/Podfile.lock
- example/ios/example.xcodeproj/project.pbxproj
- example/ios/example.xcodeproj/xcshareddata/xcschemes/example.xcscheme
- example/package.json
- ios/RCTJPushModule/JPUSHService.h
- package.json
升级iOS jpush SDK到4.9.0， 更新插件版本号为2.9.8
> 升级iOS jpush SDK到4.9.0， 更新插件版本号为2.9.8

- example/ios/example/AppDelegate.m
- example/package.json
> 更新demo的jcore版本，fixdemo警告

- ios/RCTJPushModule/RCTJPushModule.m
> ios 开放本地通知定时展示字段

- example/package.json
- index.js
- ios/RCTJPushModule/RCTJPushModule.m
- package.json
> iOS新增获取通知权限开关的接口，修改版本号为3.0.3

- index.d.ts
> 修改init参数channel名

- example/package.json
- package.json
> 更新版本号为3.0.7

- example/ios/Podfile.lock
- example/ios/example.xcodeproj/project.pbxproj
- example/ios/example/AppDelegate.mm
- example/ios/example/Info.plist
- example/ios/example/example.entitlements
> 补充iOS appdelegate.m 中的代码

- ios/RCTJPushModule/RCTJPushModule.m
> iOS 修复jpush的代理设置问题。

- package.json
> 更新版本号为3.1.2
